In [6]:
import numpy as np # linear algebra
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
%matplotlib inline

In [7]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.autograd import Variable

import torchvision

In [8]:
import set_data_2 as sd

# load train set, test set

X_train, Y_train, X_test, Y_test, y_min, y_max, y_mean, y_std = sd.set_data("data/combined_total_data_3")

# print(X_train.shape)
# print(X_train, Y_train)
# print(Y_train[0])


x_train = Variable(X_train)
y_train = Variable(Y_train)

x_test = Variable(X_test)
y_test = Variable(Y_test)

# y_test = Variable(Y_test)
for i in range(20):
    print(y_test)


----------normalize--------------
 X_Data:  [[0.4        0.52302632 0.10526316 ... 0.75657895 0.10526316 0.28571429]
 [1.         0.70065789 0.84210526 ... 0.92763158 0.10526316 0.28571429]
 [1.         0.64802632 0.10526316 ... 0.35855263 0.31578947 1.        ]
 ...
 [0.2        0.25986842 0.73684211 ... 0.34868421 0.15789474 0.71428571]
 [0.4        0.89473684 0.57894737 ... 0.10855263 0.26315789 0.28571429]
 [1.         0.01315789 0.36842105 ... 0.11184211 0.42105263 0.85714286]]
----------standarize--------------
 X_Data:  [[-0.28959094  0.0843167  -1.2989766  ...  0.88490772 -1.29980542
  -0.65438368]
 [ 1.46713074  0.69768993  1.12687148 ...  1.47596075 -1.29980542
  -0.65438368]
 [ 1.46713074  0.51594971 -1.2989766  ... -0.49042719 -0.60636297
   1.52775897]
 ...
 [-0.87516483 -0.82438438  0.78032175 ... -0.5245264  -1.12644481
   0.65490191]
 [-0.28959094  1.36785698  0.26049717 ... -1.35427392 -0.77972359
  -0.65438368]
 [ 1.46713074 -1.67629164 -0.43260228 ... -1.34290751 -0.

In [10]:
from sklearn.linear_model import LinearRegression
from sklearn.svm import LinearSVC
from sklearn.metrics import mean_squared_error, r2_score

reg = LinearRegression()
# clf = LinearSVC()

reg.fit(x_train , y_train)
# clf.fit(x_train , y_train)

y_pred = reg.predict(x_test)
# y2_pred = clf.predict(x_test)

print('Mean squared error: %.2f'
      % mean_squared_error(y_test, y_pred))
# The coefficient of determination: 1 is perfect prediction
print('Coefficient of determination: %.2f'
      % r2_score(y_test, y_pred))


Mean squared error: 0.73
Coefficient of determination: 0.42


In [11]:
def denormalize(data, d_min, d_max, d_mean, d_std):
    
    tmp_data = torch.empty([data.shape[0], data.shape[1]])
    
    for i in range(data.shape[0]):
        e = float(data[i])
        
        #tmp_data[i] = (e*d_std + d_mean)
        tmp_data[i] = (e*d_std + d_mean)*(d_max - d_min) + d_min

    return tmp_data

for i in range(20):
    print(y_test[i], y_pred[i])
# print(float(y_pred[0]))
# print(y_test.float())
# print(y_pred[0])

dy_test = denormalize(y_test, y_min, y_max, y_mean, y_std)
dy_pred = denormalize(y_pred, y_min, y_max, y_mean, y_std)

for i in range(20):
    print(dy_test[i], dy_pred[i])
# print(dy_test)
# print(dy_pred)



tensor([-0.1933], dtype=torch.float64) [0.43740502]
tensor([0.5295], dtype=torch.float64) [0.92865915]
tensor([-0.2456], dtype=torch.float64) [0.26880344]
tensor([0.0414], dtype=torch.float64) [0.62237207]
tensor([-0.9015], dtype=torch.float64) [-0.56178831]
tensor([-0.4572], dtype=torch.float64) [-0.12771472]
tensor([-0.1019], dtype=torch.float64) [0.13406722]
tensor([1.5011], dtype=torch.float64) [0.83556248]
tensor([-0.4985], dtype=torch.float64) [-0.23567386]
tensor([0.8036], dtype=torch.float64) [1.00069159]
tensor([1.1582], dtype=torch.float64) [1.68486057]
tensor([-0.1585], dtype=torch.float64) [-0.48429699]
tensor([-0.5299], dtype=torch.float64) [-0.39684738]
tensor([-0.3164], dtype=torch.float64) [-0.41715862]
tensor([0.1469], dtype=torch.float64) [0.22667645]
tensor([0.6266], dtype=torch.float64) [0.84229911]
tensor([-0.3047], dtype=torch.float64) [-0.35772301]
tensor([-0.8124], dtype=torch.float64) [-0.57259088]
tensor([-2.2230], dtype=torch.float64) [-1.91176687]
tensor([-1